name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run typecheck

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build:production
      env:
        NODE_ENV: production
        NEXT_PUBLIC_SITE_URL: https://skillquiz.ru

    - name: Create deployment package
      run: |
        # Create archive with all necessary files
        tar -czf deployment.tar.gz \
          --exclude=node_modules \
          --exclude=.git \
          --exclude=.env.local \
          --exclude=deployment.tar.gz \
          .

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "deployment.tar.gz"
        target: "/tmp/"

    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: |
          # Stop current application
          cd /home/admin/apps/skillquiz
          pm2 stop skillquiz || true
          
          # Backup current version
          if [ -d "/home/admin/apps/skillquiz" ]; then
            sudo mv /home/admin/apps/skillquiz /home/admin/apps/skillquiz-backup-$(date +%Y%m%d-%H%M%S)
          fi
          
          # Create app directory
          mkdir -p /home/admin/apps/skillquiz
          
          # Extract new deployment
          cd /home/admin/apps/skillquiz
          tar -xzf /tmp/deployment.tar.gz
          rm -f /tmp/deployment.tar.gz
          
          # Create logs directory
          mkdir -p logs
          
          # Install dependencies
          npm ci --production
          
          # Environment variables should be set in GitHub Secrets or already in the project
          
          # Start application with PM2
          pm2 start ecosystem.config.js --update-env
          pm2 save
          
          # Health check
          sleep 10
          curl -f http://localhost:3002 || exit 1
          
          echo "Deployment completed successfully!"

    - name: Notify deployment status
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Deployment ${{ job.status }} for SkillQuiz'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}